[package]
name = "wove-format"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Markdown, highlighted code, and diffs for Wove"

[dependencies]
wove = { path = "../core", version = "=0.0.1", default-features = false }
pulldown-cmark = { version = "0.13", default-features = false }
similar = "2.7"
syntect = { version = "5.3", default-features = false, features = ["default-fancy"] }
