[package]
name = "wove-dioxus"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Dioxus components for wove terminal interfaces"
readme = "README.md"

[features]
default = ["terminal"]
terminal = ["wove/terminal", "dep:futures-lite"]

[dependencies]
futures-lite = { version = "2.6.1", optional = true }
wove = { path = "../core", version = "=0.0.1", default-features = false }
dioxus-core = "=0.7.10"

[dev-dependencies]
dioxus = { version = "=0.7.10", default-features = false, features = ["macro", "hooks", "signals"] }

[[example]]
name = "counter"
required-features = ["terminal"]
