[package]
name = "wove-examples"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
wove = { path = "../core" }
wove-ssh = { path = "../ssh" }
tokio = { version = "1", features = ["rt-multi-thread", "net", "signal"] }

[[bin]]
name = "editor"
path = "src/editor.rs"

[[bin]]
name = "chess"
path = "src/chess/main.rs"
